import { IconType } from 'react-icons';

import {
	HiChevronUp,
	HiChevronDown,
	HiChevronRight,
	HiChevronLeft,
	HiOutlineArrowPath,
	HiCheck,
	HiMiniQuestionMarkCircle,
	HiMiniMinus,
	HiMiniPlus,
	HiMiniUser,
	HiMiniXMark,
	HiEyeDropper,
	HiOutlineLink,
	HiExclamationTriangle,
	HiArrowUpRight,
	HiInformationCircle,
	HiExclamationCircle,
	HiCheckCircle,
	HiChatBubbleLeftRight,
	HiPaperAirplane,
	HiArrowDownTray,
	HiCpuChip,
	HiCircleStack,
	HiCloudArrowUp,
	HiCodeBracket,
	HiCommandLine,
} from "react-icons/hi2";

import {
	FaDiscord,
	FaGithub,
	FaLinkedinIn as FaLinkedin,
	FaEnvelope,
	FaPython,
	FaReact,
	FaNodeJs,
	FaDocker,
	FaAws,
	FaGitAlt,
	FaRobot,
} from "react-icons/fa6";

import {
	SiTypescript,
	SiJavascript,
	SiNextdotjs,
	SiFastapi,
	SiPostgresql,
	SiMongodb,
	SiOpenai,
	SiLangchain,
} from "react-icons/si";

export const iconLibrary: Record<string, IconType> = {
	chevronUp: HiChevronUp,
    chevronDown: HiChevronDown,
	chevronRight: HiChevronRight,
	chevronLeft: HiChevronLeft,
	refresh: HiOutlineArrowPath,
	check: HiCheck,
	helpCircle: HiMiniQuestionMarkCircle,
	infoCircle: HiInformationCircle,
	warningTriangle: HiExclamationTriangle,
	errorCircle: HiExclamationCircle,
	checkCircle: HiCheckCircle,
	eyeDropper: HiEyeDropper,
	person: HiMiniUser,
	close: HiMiniXMark,
	openLink: HiOutlineLink,
	discord: FaDiscord,
	github: FaGithub,
	linkedin: FaLinkedin,
	email: FaEnvelope,
	arrowUpRight: HiArrowUpRight,
	minus: HiMiniMinus,
	plus: HiMiniPlus,
	chat: HiChatBubbleLeftRight,
	send: HiPaperAirplane,
	download: HiArrowDownTray,
	robot: FaRobot,
	// Tech Stack Icons
	cpu: HiCpuChip,
	database: HiCircleStack,
	cloud: HiCloudArrowUp,
	code: HiCodeBracket,
	terminal: HiCommandLine,
	python: FaPython,
	react: FaReact,
	nodejs: FaNodeJs,
	docker: FaDocker,
	aws: FaAws,
	git: FaGitAlt,
	typescript: SiTypescript,
	javascript: SiJavascript,
	nextjs: SiNextdotjs,
	fastapi: SiFastapi,
	postgresql: SiPostgresql,
	mongodb: SiMongodb,
	openai: SiOpenai,
	langchain: SiLangchain,
};