
services:
  portfolios-backend:
    build: .
    container_name: portfolios-backend
    ports:
      - "8000:8000"
    env_file:
      - .env.prod.dokploy
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
    volumes:
      # Montar vectorstores para persistencia en producción
      - ./vectorstores:/app/vectorstores
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
